################################################################################
################################################################################
################################################################################
BbSkillGroup.delete_all

sgAgility = BbSkillGroup.create(name: 'Agility')
sgGeneral = BbSkillGroup.create(name: 'General')
sgMutations = BbSkillGroup.create(name: 'Mutations')
sgPassing = BbSkillGroup.create(name: 'Passing')
sgStrength = BbSkillGroup.create(name: 'Strength')
sgTraits = BbSkillGroup.create(name: 'Traits')

################################################################################
################################################################################
################################################################################
BbSkill.delete_all

sCatch = BbSkill.create(bb_skill_group_id: sgAgility.id, name: 'Catch', must_use: false)
sDefensive = BbSkill.create(bb_skill_group_id: sgAgility.id, name: 'Defensive', must_use: false)
sDivingCatch = BbSkill.create(bb_skill_group_id: sgAgility.id, name: 'Diving Catch', must_use: false)
sDivingTackle = BbSkill.create(bb_skill_group_id: sgAgility.id, name: 'Diving Tackle', must_use: false)
sDodge = BbSkill.create(bb_skill_group_id: sgAgility.id, name: 'Dodge', must_use: false)
sJumpUp = BbSkill.create(bb_skill_group_id: sgAgility.id, name: 'Jump Up', must_use: false)
sLeap = BbSkill.create(bb_skill_group_id: sgAgility.id, name: 'Leap', must_use: false)
sSafePairofHands = BbSkill.create(bb_skill_group_id: sgAgility.id, name: 'Safe Pair of Hands', must_use: false)
sSidestep = BbSkill.create(bb_skill_group_id: sgAgility.id, name: 'Sidestep', must_use: false)
sSneakyGit = BbSkill.create(bb_skill_group_id: sgAgility.id, name: 'Sneaky Git', must_use: false)
sSprint = BbSkill.create(bb_skill_group_id: sgAgility.id, name: 'Sprint', must_use: false)
sSureFeet = BbSkill.create(bb_skill_group_id: sgAgility.id, name: 'Sure Feet', must_use: false)
sBlock = BbSkill.create(bb_skill_group_id: sgGeneral.id, name: 'Block', must_use: false)
sDauntless = BbSkill.create(bb_skill_group_id: sgGeneral.id, name: 'Dauntless', must_use: false)
sDirtyPlayer = BbSkill.create(bb_skill_group_id: sgGeneral.id, name: 'Dirty Player', must_use: false)
sFend = BbSkill.create(bb_skill_group_id: sgGeneral.id, name: 'Fend', must_use: false)
sFrenzy = BbSkill.create(bb_skill_group_id: sgGeneral.id, name: 'Frenzy', must_use: true)
sKick = BbSkill.create(bb_skill_group_id: sgGeneral.id, name: 'Kick', must_use: false)
sPro = BbSkill.create(bb_skill_group_id: sgGeneral.id, name: 'Pro', must_use: false)
sShadowing = BbSkill.create(bb_skill_group_id: sgGeneral.id, name: 'Shadowing', must_use: false)
sStripBall = BbSkill.create(bb_skill_group_id: sgGeneral.id, name: 'Strip Ball', must_use: false)
sSureHands = BbSkill.create(bb_skill_group_id: sgGeneral.id, name: 'Sure Hands', must_use: false)
sTackle = BbSkill.create(bb_skill_group_id: sgGeneral.id, name: 'Tackle', must_use: false)
sWrestle = BbSkill.create(bb_skill_group_id: sgGeneral.id, name: 'Wrestle', must_use: false)
sBigHands = BbSkill.create(bb_skill_group_id: sgMutations.id, name: 'Big Hands', must_use: false)
sClaws = BbSkill.create(bb_skill_group_id: sgMutations.id, name: 'Claws', must_use: false)
sDisturbingPresence = BbSkill.create(bb_skill_group_id: sgMutations.id, name: 'Disturbing Presence', must_use: true)
sExtraArms = BbSkill.create(bb_skill_group_id: sgMutations.id, name: 'Extra Arms', must_use: false)
sFoulAppearance = BbSkill.create(bb_skill_group_id: sgMutations.id, name: 'Foul Appearance', must_use: true)
sHorns = BbSkill.create(bb_skill_group_id: sgMutations.id, name: 'Horns', must_use: false)
sIronHardSkin = BbSkill.create(bb_skill_group_id: sgMutations.id, name: 'Iron Hard Skin', must_use: false)
sMonstrousMouth = BbSkill.create(bb_skill_group_id: sgMutations.id, name: 'Monstrous Mouth', must_use: false)
sPrehensileTail = BbSkill.create(bb_skill_group_id: sgMutations.id, name: 'Prehensile Tail', must_use: false)
sTentacles = BbSkill.create(bb_skill_group_id: sgMutations.id, name: 'Tentacles', must_use: false)
sTwoHeads = BbSkill.create(bb_skill_group_id: sgMutations.id, name: 'Two Heads', must_use: false)
sVeryLongLegs = BbSkill.create(bb_skill_group_id: sgMutations.id, name: 'Very Long Legs', must_use: false)
sAccurate = BbSkill.create(bb_skill_group_id: sgPassing.id, name: 'Accurate', must_use: false)
sCannoneer = BbSkill.create(bb_skill_group_id: sgPassing.id, name: 'Cannoneer', must_use: false)
sCloudBurster = BbSkill.create(bb_skill_group_id: sgPassing.id, name: 'Cloud Burster', must_use: false)
sDumpOff = BbSkill.create(bb_skill_group_id: sgPassing.id, name: 'Dump Off', must_use: false)
sFumblerooskie = BbSkill.create(bb_skill_group_id: sgPassing.id, name: 'Fumblerooskie', must_use: false)
sHailMaryPass = BbSkill.create(bb_skill_group_id: sgPassing.id, name: 'Hail Mary Pass', must_use: false)
sLeader = BbSkill.create(bb_skill_group_id: sgPassing.id, name: 'Leader', must_use: false)
sNervesofSteel = BbSkill.create(bb_skill_group_id: sgPassing.id, name: 'Nerves of Steel', must_use: false)
sOntheBall = BbSkill.create(bb_skill_group_id: sgPassing.id, name: 'On the Ball', must_use: false)
sPass = BbSkill.create(bb_skill_group_id: sgPassing.id, name: 'Pass', must_use: false)
sRunningPass = BbSkill.create(bb_skill_group_id: sgPassing.id, name: 'Running Pass', must_use: false)
sSafePass = BbSkill.create(bb_skill_group_id: sgPassing.id, name: 'Safe Pass', must_use: false)
sArmBar = BbSkill.create(bb_skill_group_id: sgStrength.id, name: 'Arm Bar', must_use: false)
sBrawler = BbSkill.create(bb_skill_group_id: sgStrength.id, name: 'Brawler', must_use: false)
sBreakTackle = BbSkill.create(bb_skill_group_id: sgStrength.id, name: 'Break Tackle', must_use: false)
sGrab = BbSkill.create(bb_skill_group_id: sgStrength.id, name: 'Grab', must_use: false)
sGuard = BbSkill.create(bb_skill_group_id: sgStrength.id, name: 'Guard', must_use: false)
sJuggernaught = BbSkill.create(bb_skill_group_id: sgStrength.id, name: 'Juggernaught', must_use: false)
sMightyBlow = BbSkill.create(bb_skill_group_id: sgStrength.id, name: 'Mighty Blow', must_use: false)
sMultipleBlock = BbSkill.create(bb_skill_group_id: sgStrength.id, name: 'Multiple Block', must_use: false)
sPileDriver = BbSkill.create(bb_skill_group_id: sgStrength.id, name: 'Pile Driver', must_use: false)
sStandFirm = BbSkill.create(bb_skill_group_id: sgStrength.id, name: 'Stand Firm', must_use: false)
sStrongArm = BbSkill.create(bb_skill_group_id: sgStrength.id, name: 'Strong Arm', must_use: false)
sThickSkull = BbSkill.create(bb_skill_group_id: sgStrength.id, name: 'Thick Skull', must_use: false)
sAlwaysHungry = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Always Hungry', must_use: true)
sAnimalSavagery = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Animal Savagery', must_use: true)
sAnimosity = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Animosity', must_use: true)
sBallandChain = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Ball and Chain', must_use: true)
sBombardier = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Bombardier', must_use: false)
sBoneHead = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Bone Head', must_use: true)
sChainsaw = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Chainsaw', must_use: true)
sDecay = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Decay', must_use: true)
sHyponoticGaze = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Hyponotic Gaze', must_use: false)
sKickTeammate = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Kick Team-mate', must_use: false)
sLoner = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Loner', must_use: true)
sNoHands = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'No Hands', must_use: true)
sPlagueRidden = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Plague Ridden', must_use: false)
sPogoStick = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Pogo Stick', must_use: false)
sProjectileVomit = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Projectile Vomit', must_use: false)
sReallyStupid = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Really Stupid', must_use: true)
sRegeneration = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Regeneration', must_use: false)
sRightStuff = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Right Stuff', must_use: true)
sSecretWeapon = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Secret Weapon', must_use: true)
sStab = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Stab', must_use: false)
sStunty = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Stunty', must_use: true)
sSwarming = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Swarming', must_use: false)
sSwoop = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Swoop', must_use: false)
sTakeRoot = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Take Root', must_use: true)
sThrowTeammate = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Throw Team-mate', must_use: false)
sTimber = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Timmm-ber!', must_use: false)
sTitchy = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Titchy', must_use: true)
sUnchannelledFury = BbSkill.create(bb_skill_group_id: sgTraits.id, name: 'Unchannelled Fury', must_use: true)

################################################################################
################################################################################
################################################################################
BbSpecialRule.delete_all

srBadlandsBrawl = BbSpecialRule.create(name: 'Badlands Brawl')
srElvenKingdomLeague = BbSpecialRule.create(name: 'Elven Kingdom League')
srHalflingThimbleCup = BbSpecialRule.create(name: 'Halfling Thimble Cup')
srLustrianSuperleague = BbSpecialRule.create(name: 'Lustrian Superleague')
srOldWorldClassic = BbSpecialRule.create(name: 'Old World Classic')
srSylvanianSpotlight = BbSpecialRule.create(name: 'Sylvanian Spotlight')
srUnderworldsChallenge = BbSpecialRule.create(name: 'Underworlds Challenge')
srWorldEdgeSuperleague = BbSpecialRule.create(name: 'World Edge Superleague')
srBriberyandCorruption = BbSpecialRule.create(name: 'Bribery and Corruption')
srFavouredof = BbSpecialRule.create(name: 'Favoured of...')
srLowCostLinemen = BbSpecialRule.create(name: 'Low Cost Linemen')
srMasterofUndeath = BbSpecialRule.create(name: 'Masters of Undeath')

################################################################################
################################################################################
################################################################################
Faction.where(ladder_name: '/bloodbowl').delete_all

fBlackOrc = Faction.create(faction_name: 'Black Orc', ladder_name: '/bloodbowl')
fChaosChosen = Faction.create(faction_name: 'Chaos Chosen', ladder_name: '/bloodbowl')
fChaosRenegade = Faction.create(faction_name: 'Chaos Renegade', ladder_name: '/bloodbowl')
fDarkElf = Faction.create(faction_name: 'Dark Elf', ladder_name: '/bloodbowl')
fDwarf = Faction.create(faction_name: 'Dwarf', ladder_name: '/bloodbowl')
fElvenUnion = Faction.create(faction_name: 'Elven Union', ladder_name: '/bloodbowl')
fGoblin = Faction.create(faction_name: 'Goblin', ladder_name: '/bloodbowl')
fHalfling = Faction.create(faction_name: 'Halfling', ladder_name: '/bloodbowl')
fHuman = Faction.create(faction_name: 'Human', ladder_name: '/bloodbowl')
fImperialNobility = Faction.create(faction_name: 'Imperial Nobility', ladder_name: '/bloodbowl')
fLizardmen = Faction.create(faction_name: 'Lizardmen', ladder_name: '/bloodbowl')
fNecromanticHorror = Faction.create(faction_name: 'Necromantic Horror', ladder_name: '/bloodbowl')
fNurgle = Faction.create(faction_name: 'Nurgle', ladder_name: '/bloodbowl')
fOgre = Faction.create(faction_name: 'Ogre', ladder_name: '/bloodbowl')
fOldWorldAlliance = Faction.create(faction_name: 'Old World Alliance', ladder_name: '/bloodbowl')
fOrc = Faction.create(faction_name: 'Orc', ladder_name: '/bloodbowl')
fShamblingUndead = Faction.create(faction_name: 'Shambling Undead', ladder_name: '/bloodbowl')
fSkaven = Faction.create(faction_name: 'Skaven', ladder_name: '/bloodbowl')
fSnotling = Faction.create(faction_name: 'Snotling', ladder_name: '/bloodbowl')
fUnderworldDenizens = Faction.create(faction_name: 'Underworld Denizens', ladder_name: '/bloodbowl')
fWoodElf = Faction.create(faction_name: 'Wood Elf', ladder_name: '/bloodbowl')

################################################################################
################################################################################
################################################################################
BbTeamTemplate.delete_all

teamtemplateBlackOrc = BbTeamTemplate.create(faction_id: fBlackOrc.id, reroll_cost: 60000, tier: 2, apothecary: true)
teamtemplateChaosChosen = BbTeamTemplate.create(faction_id: fChaosChosen.id, reroll_cost: 60000, tier: 2, apothecary: true)
teamtemplateChaosRenegade = BbTeamTemplate.create(faction_id: fChaosRenegade.id, reroll_cost: 70000, tier: 2, apothecary: true)
teamtemplateDarkElf = BbTeamTemplate.create(faction_id: fDarkElf.id, reroll_cost: 50000, tier: 1, apothecary: true)
teamtemplateDwarf = BbTeamTemplate.create(faction_id: fDwarf.id, reroll_cost: 50000, tier: 1, apothecary: true)
teamtemplateElvenUnion = BbTeamTemplate.create(faction_id: fElvenUnion.id, reroll_cost: 50000, tier: 2, apothecary: true)
teamtemplateGoblin = BbTeamTemplate.create(faction_id: fGoblin.id, reroll_cost: 60000, tier: 3, apothecary: true)
teamtemplateHalfling = BbTeamTemplate.create(faction_id: fHalfling.id, reroll_cost: 60000, tier: 3, apothecary: true)
teamtemplateHuman = BbTeamTemplate.create(faction_id: fHuman.id, reroll_cost: 50000, tier: 1, apothecary: true)
teamtemplateImperialNobility = BbTeamTemplate.create(faction_id: fImperialNobility.id, reroll_cost: 70000, tier: 2, apothecary: true)
teamtemplateLizardmen = BbTeamTemplate.create(faction_id: fLizardmen.id, reroll_cost: 70000, tier: 1, apothecary: true)
teamtemplateNecromanticHorror = BbTeamTemplate.create(faction_id: fNecromanticHorror.id, reroll_cost: 70000, tier: 2, apothecary: false)
teamtemplateNurgle = BbTeamTemplate.create(faction_id: fNurgle.id, reroll_cost: 70000, tier: 2, apothecary: false)
teamtemplateOgre = BbTeamTemplate.create(faction_id: fOgre.id, reroll_cost: 70000, tier: 3, apothecary: true)
teamtemplateOldWorldAlliance = BbTeamTemplate.create(faction_id: fOldWorldAlliance.id, reroll_cost: 70000, tier: 1, apothecary: true)
teamtemplateOrc = BbTeamTemplate.create(faction_id: fOrc.id, reroll_cost: 60000, tier: 1, apothecary: true)
teamtemplateShamblingUndead = BbTeamTemplate.create(faction_id: fShamblingUndead.id, reroll_cost: 70000, tier: 1, apothecary: false)
teamtemplateSkaven = BbTeamTemplate.create(faction_id: fSkaven.id, reroll_cost: 60000, tier: 1, apothecary: true)
teamtemplateSnotling = BbTeamTemplate.create(faction_id: fSnotling.id, reroll_cost: 60000, tier: 3, apothecary: true)
teamtemplateUnderworldDenizens = BbTeamTemplate.create(faction_id: fUnderworldDenizens.id, reroll_cost: 70000, tier: 2, apothecary: true)
teamtemplateWoodElf = BbTeamTemplate.create(faction_id: fWoodElf.id, reroll_cost: 50000, tier: 1, apothecary: true)

################################################################################
################################################################################
################################################################################
BbTeamSpecialRule.delete_all

BbTeamSpecialRule.create(bb_special_rule_id: srBadlandsBrawl.id, bb_team_template_id: teamtemplateBlackOrc.id)
BbTeamSpecialRule.create(bb_special_rule_id: srBriberyandCorruption.id, bb_team_template_id: teamtemplateBlackOrc.id)
BbTeamSpecialRule.create(bb_special_rule_id: srFavouredof.id, bb_team_template_id: teamtemplateChaosChosen.id)
BbTeamSpecialRule.create(bb_special_rule_id: srFavouredof.id, bb_team_template_id: teamtemplateChaosRenegade.id)
BbTeamSpecialRule.create(bb_special_rule_id: srElvenKingdomLeague.id, bb_team_template_id: teamtemplateDarkElf.id)
BbTeamSpecialRule.create(bb_special_rule_id: srOldWorldClassic.id, bb_team_template_id: teamtemplateDwarf.id)
BbTeamSpecialRule.create(bb_special_rule_id: srWorldEdgeSuperleague.id, bb_team_template_id: teamtemplateDwarf.id)
BbTeamSpecialRule.create(bb_special_rule_id: srElvenKingdomLeague.id, bb_team_template_id: teamtemplateElvenUnion.id)
BbTeamSpecialRule.create(bb_special_rule_id: srBadlandsBrawl.id, bb_team_template_id: teamtemplateGoblin.id)
BbTeamSpecialRule.create(bb_special_rule_id: srBriberyandCorruption.id, bb_team_template_id: teamtemplateGoblin.id)
BbTeamSpecialRule.create(bb_special_rule_id: srUnderworldsChallenge.id, bb_team_template_id: teamtemplateGoblin.id)
BbTeamSpecialRule.create(bb_special_rule_id: srHalflingThimbleCup.id, bb_team_template_id: teamtemplateHalfling.id)
BbTeamSpecialRule.create(bb_special_rule_id: srOldWorldClassic.id, bb_team_template_id: teamtemplateHalfling.id)
BbTeamSpecialRule.create(bb_special_rule_id: srOldWorldClassic.id, bb_team_template_id: teamtemplateHuman.id)
BbTeamSpecialRule.create(bb_special_rule_id: srOldWorldClassic.id, bb_team_template_id: teamtemplateImperialNobility.id)
BbTeamSpecialRule.create(bb_special_rule_id: srLustrianSuperleague.id, bb_team_template_id: teamtemplateLizardmen.id)
BbTeamSpecialRule.create(bb_special_rule_id: srMasterofUndeath.id, bb_team_template_id: teamtemplateNecromanticHorror.id)
BbTeamSpecialRule.create(bb_special_rule_id: srSylvanianSpotlight.id, bb_team_template_id: teamtemplateNecromanticHorror.id)
BbTeamSpecialRule.create(bb_special_rule_id: srFavouredof.id, bb_team_template_id: teamtemplateNurgle.id)
BbTeamSpecialRule.create(bb_special_rule_id: srBadlandsBrawl.id, bb_team_template_id: teamtemplateOgre.id)
BbTeamSpecialRule.create(bb_special_rule_id: srLowCostLinemen.id, bb_team_template_id: teamtemplateOgre.id)
BbTeamSpecialRule.create(bb_special_rule_id: srOldWorldClassic.id, bb_team_template_id: teamtemplateOgre.id)
BbTeamSpecialRule.create(bb_special_rule_id: srOldWorldClassic.id, bb_team_template_id: teamtemplateOldWorldAlliance.id)
BbTeamSpecialRule.create(bb_special_rule_id: srBadlandsBrawl.id, bb_team_template_id: teamtemplateOrc.id)
BbTeamSpecialRule.create(bb_special_rule_id: srSylvanianSpotlight.id, bb_team_template_id: teamtemplateShamblingUndead.id)
BbTeamSpecialRule.create(bb_special_rule_id: srMasterofUndeath.id, bb_team_template_id: teamtemplateShamblingUndead.id)
BbTeamSpecialRule.create(bb_special_rule_id: srUnderworldsChallenge.id, bb_team_template_id: teamtemplateSkaven.id)
BbTeamSpecialRule.create(bb_special_rule_id: srBriberyandCorruption.id, bb_team_template_id: teamtemplateSnotling.id)
BbTeamSpecialRule.create(bb_special_rule_id: srLowCostLinemen.id, bb_team_template_id: teamtemplateSnotling.id)
BbTeamSpecialRule.create(bb_special_rule_id: srUnderworldsChallenge.id, bb_team_template_id: teamtemplateSnotling.id)
BbTeamSpecialRule.create(bb_special_rule_id: srBriberyandCorruption.id, bb_team_template_id: teamtemplateUnderworldDenizens.id)
BbTeamSpecialRule.create(bb_special_rule_id: srUnderworldsChallenge.id, bb_team_template_id: teamtemplateUnderworldDenizens.id)
BbTeamSpecialRule.create(bb_special_rule_id: srElvenKingdomLeague.id, bb_team_template_id: teamtemplateWoodElf.id)











################################################################################
#                                                                              #
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ #
#                              All done up here!                               #
#                                                                              #
#                                                                              #
#                          Need more work down here!                           #
# \/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/ #
################################################################################





################################################################################
################################################################################
################################################################################
BbPlayerTemplate.delete_all

teamBlackOrcplayerGoblinBruiserLineman = BbPlayerTemplate.create(bb_team_template_id: teamtemplateBlackOrc.id,position_name: 'Goblin Bruiser Lineman', max_allowed: 12, cost: 45000, ma: 6, st: 2, ag: 3, pa: 4, av: 8)
teamBlackOrcplayerBlackOrc = BbPlayerTemplate.create(bb_team_template_id: teamtemplateBlackOrc.id,position_name: 'Black Orc', max_allowed: 6, cost: 90000, ma: 4, st: 4, ag: 4, pa: 5, av: 10)
teamBlackOrcplayerTrainedTroll = BbPlayerTemplate.create(bb_team_template_id: teamtemplateBlackOrc.id,position_name: 'Trained Troll', max_allowed: 1, cost: 115000, ma: 4, st: 5, ag: 5, pa: 5, av: 10)
teamChaosChosenplayerBeastmanRunnerLineman = BbPlayerTemplate.create(bb_team_template_id: teamtemplateChaosChosen.id,position_name: 'Beastman Runner Lineman', max_allowed: 16, cost: 60000, ma: 6, st: 3, ag: 3, pa: 4, av: 9)
teamChaosChosenplayerChosenBlocker = BbPlayerTemplate.create(bb_team_template_id: teamtemplateChaosChosen.id,position_name: 'Chosen Blocker', max_allowed: 4, cost: 100000, ma: 5, st: 4, ag: 3, pa: 5, av: 10)
teamChaosChosenplayerChaosTroll = BbPlayerTemplate.create(bb_team_template_id: teamtemplateChaosChosen.id,position_name: 'Chaos Troll', max_allowed: 1, cost: 115000, ma: 4, st: 5, ag: 5, pa: 5, av: 10)
teamChaosChosenplayerChaosOgre = BbPlayerTemplate.create(bb_team_template_id: teamtemplateChaosChosen.id,position_name: 'Chaos Ogre', max_allowed: 1, cost: 140000, ma: 5, st: 5, ag: 4, pa: 5, av: 10)
teamChaosChosenplayerMinotaur = BbPlayerTemplate.create(bb_team_template_id: teamtemplateChaosChosen.id,position_name: 'Minotaur', max_allowed: 1, cost: 150000, ma: 5, st: 5, ag: 4, pa: 0, av: 9)
teamChaosRenegadeplayerRenegadeHumanLineman = BbPlayerTemplate.create(bb_team_template_id: teamtemplateChaosRenegade.id,position_name: 'Renegade Human Lineman', max_allowed: 12, cost: 50000, ma: 6, st: 3, ag: 3, pa: 4, av: 9)
teamChaosRenegadeplayerRenegadeHumanThrower = BbPlayerTemplate.create(bb_team_template_id: teamtemplateChaosRenegade.id,position_name: 'Renegade Human Thrower', max_allowed: 1, cost: 75000, ma: 6, st: 3, ag: 3, pa: 3, av: 9)
teamChaosRenegadeplayerRenegadeGoblin = BbPlayerTemplate.create(bb_team_template_id: teamtemplateChaosRenegade.id,position_name: 'Renegade Goblin', max_allowed: 1, cost: 40000, ma: 6, st: 2, ag: 3, pa: 4, av: 8)
teamChaosRenegadeplayerRenegadeOrc = BbPlayerTemplate.create(bb_team_template_id: teamtemplateChaosRenegade.id,position_name: 'Renegade Orc', max_allowed: 1, cost: 50000, ma: 5, st: 3, ag: 3, pa: 5, av: 10)
teamChaosRenegadeplayerRenegadeSkaven = BbPlayerTemplate.create(bb_team_template_id: teamtemplateChaosRenegade.id,position_name: 'Renegade Skaven', max_allowed: 1, cost: 50000, ma: 7, st: 3, ag: 3, pa: 4, av: 8)
teamChaosRenegadeplayerRenegadeDarkElf = BbPlayerTemplate.create(bb_team_template_id: teamtemplateChaosRenegade.id,position_name: 'Renegade Dark Elf', max_allowed: 1, cost: 75000, ma: 6, st: 3, ag: 2, pa: 3, av: 9)
teamChaosRenegadeplayerRenegadeTroll = BbPlayerTemplate.create(bb_team_template_id: teamtemplateChaosRenegade.id,position_name: 'Renegade Troll', max_allowed: 1, cost: 115000, ma: 4, st: 5, ag: 5, pa: 4, av: 10)
teamChaosRenegadeplayerRenegadeOgre = BbPlayerTemplate.create(bb_team_template_id: teamtemplateChaosRenegade.id,position_name: 'Renegade Ogre', max_allowed: 1, cost: 140000, ma: 5, st: 5, ag: 4, pa: 4, av: 10)
teamChaosRenegadeplayerRenegadeMinotaur = BbPlayerTemplate.create(bb_team_template_id: teamtemplateChaosRenegade.id,position_name: 'Renegade Minotaur', max_allowed: 1, cost: 150000, ma: 5, st: 5, ag: 4, pa: 0, av: 9)
teamChaosRenegadeplayerRenegadeRatOgre = BbPlayerTemplate.create(bb_team_template_id: teamtemplateChaosRenegade.id,position_name: 'Renegade Rat Ogre', max_allowed: 1, cost: 150000, ma: 6, st: 5, ag: 4, pa: 0, av: 9)
teamDarkElfplayerDarkElfLineman = BbPlayerTemplate.create(bb_team_template_id: teamtemplateDarkElf.id,position_name: 'Dark Elf Lineman', max_allowed: 12, cost: 70000, ma: 6, st: 3, ag: 2, pa: 4, av: 9)
teamDarkElfplayerRunner = BbPlayerTemplate.create(bb_team_template_id: teamtemplateDarkElf.id,position_name: 'Runner', max_allowed: 2, cost: 80000, ma: 7, st: 3, ag: 2, pa: 3, av: 8)
teamDarkElfplayerBlitzer = BbPlayerTemplate.create(bb_team_template_id: teamtemplateDarkElf.id,position_name: 'Blitzer', max_allowed: 4, cost: 100000, ma: 7, st: 3, ag: 2, pa: 4, av: 9)
teamDarkElfplayerAssassin = BbPlayerTemplate.create(bb_team_template_id: teamtemplateDarkElf.id,position_name: 'Assassin', max_allowed: 2, cost: 85000, ma: 7, st: 3, ag: 2, pa: 5, av: 8)
teamDarkElfplayerWitchElf = BbPlayerTemplate.create(bb_team_template_id: teamtemplateDarkElf.id,position_name: 'Witch Elf', max_allowed: 2, cost: 110000, ma: 7, st: 3, ag: 2, pa: 5, av: 8)
teamDwarfplayerDwarfBlockerLineman = BbPlayerTemplate.create(bb_team_template_id: teamtemplateDwarf.id,position_name: 'Dwarf Blocker Lineman', max_allowed: 12, cost: 70000, ma: 4, st: 3, ag: 4, pa: 5, av: 10)
teamDwarfplayerRunner = BbPlayerTemplate.create(bb_team_template_id: teamtemplateDwarf.id,position_name: 'Runner', max_allowed: 2, cost: 85000, ma: 6, st: 3, ag: 3, pa: 4, av: 9)
teamDwarfplayerBlitzer = BbPlayerTemplate.create(bb_team_template_id: teamtemplateDwarf.id,position_name: 'Blitzer', max_allowed: 2, cost: 80000, ma: 5, st: 3, ag: 3, pa: 4, av: 10)
teamDwarfplayerTrollSlayer = BbPlayerTemplate.create(bb_team_template_id: teamtemplateDwarf.id,position_name: 'Troll Slayer', max_allowed: 2, cost: 95000, ma: 5, st: 3, ag: 4, pa: 0, av: 9)
teamDwarfplayerDeathRoller = BbPlayerTemplate.create(bb_team_template_id: teamtemplateDwarf.id,position_name: 'Death Roller', max_allowed: 1, cost: 170000, ma: 4, st: 7, ag: 5, pa: 0, av: 11)

################################################################################
################################################################################
################################################################################
BbPlayerSkillGroup.delete_all

BbPlayerSkillGroup.create(bb_player_template_id: teamBlackOrcplayerGoblinBruiserLineman.id, bb_skill_group_id: sgAgility.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamBlackOrcplayerGoblinBruiserLineman.id, bb_skill_group_id: sgGeneral.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamBlackOrcplayerGoblinBruiserLineman.id, bb_skill_group_id: sgPassing.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamBlackOrcplayerGoblinBruiserLineman.id, bb_skill_group_id: sgStrength.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamBlackOrcplayerBlackOrc.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamBlackOrcplayerBlackOrc.id, bb_skill_group_id: sgGeneral.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamBlackOrcplayerBlackOrc.id, bb_skill_group_id: sgPassing.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamBlackOrcplayerBlackOrc.id, bb_skill_group_id: sgStrength.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamBlackOrcplayerTrainedTroll.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamBlackOrcplayerTrainedTroll.id, bb_skill_group_id: sgGeneral.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamBlackOrcplayerTrainedTroll.id, bb_skill_group_id: sgPassing.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamBlackOrcplayerTrainedTroll.id, bb_skill_group_id: sgStrength.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerBeastmanRunnerLineman.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerBeastmanRunnerLineman.id, bb_skill_group_id: sgGeneral.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerBeastmanRunnerLineman.id, bb_skill_group_id: sgMutations.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerBeastmanRunnerLineman.id, bb_skill_group_id: sgPassing.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerBeastmanRunnerLineman.id, bb_skill_group_id: sgStrength.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerChosenBlocker.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerChosenBlocker.id, bb_skill_group_id: sgGeneral.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerChosenBlocker.id, bb_skill_group_id: sgMutations.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerChosenBlocker.id, bb_skill_group_id: sgStrength.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerChaosTroll.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerChaosTroll.id, bb_skill_group_id: sgGeneral.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerChaosTroll.id, bb_skill_group_id: sgMutations.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerChaosTroll.id, bb_skill_group_id: sgStrength.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerChaosOgre.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerChaosOgre.id, bb_skill_group_id: sgGeneral.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerChaosOgre.id, bb_skill_group_id: sgMutations.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerChaosOgre.id, bb_skill_group_id: sgStrength.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerMinotaur.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerMinotaur.id, bb_skill_group_id: sgGeneral.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerMinotaur.id, bb_skill_group_id: sgMutations.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosChosenplayerMinotaur.id, bb_skill_group_id: sgStrength.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeHumanLineman.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeHumanLineman.id, bb_skill_group_id: sgGeneral.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeHumanLineman.id, bb_skill_group_id: sgMutations.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeHumanLineman.id, bb_skill_group_id: sgStrength.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeHumanThrower.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeHumanThrower.id, bb_skill_group_id: sgGeneral.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeHumanThrower.id, bb_skill_group_id: sgMutations.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeHumanThrower.id, bb_skill_group_id: sgPassing.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeHumanThrower.id, bb_skill_group_id: sgStrength.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeGoblin.id, bb_skill_group_id: sgAgility.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeGoblin.id, bb_skill_group_id: sgGeneral.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeGoblin.id, bb_skill_group_id: sgMutations.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeGoblin.id, bb_skill_group_id: sgPassing.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeOrc.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeOrc.id, bb_skill_group_id: sgGeneral.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeOrc.id, bb_skill_group_id: sgMutations.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeOrc.id, bb_skill_group_id: sgStrength.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeSkaven.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeSkaven.id, bb_skill_group_id: sgGeneral.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeSkaven.id, bb_skill_group_id: sgMutations.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeSkaven.id, bb_skill_group_id: sgStrength.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeDarkElf.id, bb_skill_group_id: sgAgility.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeDarkElf.id, bb_skill_group_id: sgGeneral.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeDarkElf.id, bb_skill_group_id: sgMutations.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeDarkElf.id, bb_skill_group_id: sgPassing.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeDarkElf.id, bb_skill_group_id: sgStrength.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeTroll.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeTroll.id, bb_skill_group_id: sgGeneral.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeTroll.id, bb_skill_group_id: sgMutations.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeTroll.id, bb_skill_group_id: sgStrength.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeOgre.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeOgre.id, bb_skill_group_id: sgGeneral.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeOgre.id, bb_skill_group_id: sgMutations.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeOgre.id, bb_skill_group_id: sgStrength.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeMinotaur.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeMinotaur.id, bb_skill_group_id: sgGeneral.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeMinotaur.id, bb_skill_group_id: sgMutations.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeMinotaur.id, bb_skill_group_id: sgStrength.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeRatOgre.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeRatOgre.id, bb_skill_group_id: sgGeneral.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeRatOgre.id, bb_skill_group_id: sgMutations.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamChaosRenegadeplayerRenegadeRatOgre.id, bb_skill_group_id: sgStrength.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerDarkElfLineman.id, bb_skill_group_id: sgAgility.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerDarkElfLineman.id, bb_skill_group_id: sgGeneral.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerDarkElfLineman.id, bb_skill_group_id: sgStrength.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerRunner.id, bb_skill_group_id: sgAgility.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerRunner.id, bb_skill_group_id: sgGeneral.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerRunner.id, bb_skill_group_id: sgPassing.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerRunner.id, bb_skill_group_id: sgStrength.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerBlitzer.id, bb_skill_group_id: sgAgility.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerBlitzer.id, bb_skill_group_id: sgGeneral.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerBlitzer.id, bb_skill_group_id: sgPassing.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerBlitzer.id, bb_skill_group_id: sgStrength.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerAssassin.id, bb_skill_group_id: sgAgility.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerAssassin.id, bb_skill_group_id: sgGeneral.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerAssassin.id, bb_skill_group_id: sgPassing.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerAssassin.id, bb_skill_group_id: sgStrength.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerWitchElf.id, bb_skill_group_id: sgAgility.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerWitchElf.id, bb_skill_group_id: sgGeneral.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerWitchElf.id, bb_skill_group_id: sgPassing.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamDarkElfplayerWitchElf.id, bb_skill_group_id: sgStrength.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamDwarfplayerDwarfBlockerLineman.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamDwarfplayerDwarfBlockerLineman.id, bb_skill_group_id: sgGeneral.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDwarfplayerDwarfBlockerLineman.id, bb_skill_group_id: sgStrength.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDwarfplayerRunner.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamDwarfplayerRunner.id, bb_skill_group_id: sgGeneral.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDwarfplayerRunner.id, bb_skill_group_id: sgPassing.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDwarfplayerRunner.id, bb_skill_group_id: sgStrength.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamDwarfplayerBlitzer.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamDwarfplayerBlitzer.id, bb_skill_group_id: sgGeneral.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDwarfplayerBlitzer.id, bb_skill_group_id: sgPassing.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamDwarfplayerBlitzer.id, bb_skill_group_id: sgStrength.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDwarfplayerTrollSlayer.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamDwarfplayerTrollSlayer.id, bb_skill_group_id: sgGeneral.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDwarfplayerTrollSlayer.id, bb_skill_group_id: sgStrength.id, primary: true)
BbPlayerSkillGroup.create(bb_player_template_id: teamDwarfplayerDeathRoller.id, bb_skill_group_id: sgAgility.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamDwarfplayerDeathRoller.id, bb_skill_group_id: sgGeneral.id, primary: false)
BbPlayerSkillGroup.create(bb_player_template_id: teamDwarfplayerDeathRoller.id, bb_skill_group_id: sgStrength.id, primary: true)

################################################################################
################################################################################
################################################################################
BbPlayerTemplateSkill.delete_all

BbPlayerTemplateSkill.create(bb_player_template_id: teamBlackOrcplayerGoblinBruiserLineman.id, bb_skill_id: sDodge.id)
BbPlayerTemplateSkill.create(bb_player_template_id: teamBlackOrcplayerGoblinBruiserLineman.id, bb_skill_id: sRightStuff.id)
BbPlayerTemplateSkill.create(bb_player_template_id: teamBlackOrcplayerGoblinBruiserLineman.id, bb_skill_id: sStunty.id)
BbPlayerTemplateSkill.create(bb_player_template_id: teamBlackOrcplayerGoblinBruiserLineman.id, bb_skill_id: sThickSkull.id)
BbPlayerTemplateSkill.create(bb_player_template_id: teamBlackOrcplayerBlackOrc.id, bb_skill_id: sBrawler.id)
BbPlayerTemplateSkill.create(bb_player_template_id: teamBlackOrcplayerBlackOrc.id, bb_skill_id: sGrab.id)
BbPlayerTemplateSkill.create(bb_player_template_id: teamBlackOrcplayerTrainedTroll.id, bb_skill_id: sAlwaysHungry.id)
BbPlayerTemplateSkill.create(bb_player_template_id: teamBlackOrcplayerTrainedTroll.id, bb_skill_id: sLoner.id, modifier: '3+')
BbPlayerTemplateSkill.create(bb_player_template_id: teamBlackOrcplayerTrainedTroll.id, bb_skill_id: sMightyBlow.id, modifier: '+1')
BbPlayerTemplateSkill.create(bb_player_template_id: teamBlackOrcplayerTrainedTroll.id, bb_skill_id: sProjectileVomit.id)
BbPlayerTemplateSkill.create(bb_player_template_id: teamBlackOrcplayerTrainedTroll.id, bb_skill_id: sReallyStupid.id)
BbPlayerTemplateSkill.create(bb_player_template_id: teamBlackOrcplayerTrainedTroll.id, bb_skill_id: sRegeneration.id)
BbPlayerTemplateSkill.create(bb_player_template_id: teamBlackOrcplayerTrainedTroll.id, bb_skill_id: sThrowTeammate.id)
