class AddFactionIdToTeams < ActiveRecord::Migration[5.2]
  Faction.create!(faction_name: 'Transition', ladder_name: '/40k')

  Faction.create!(faction_name: 'Adeptus Astartes', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Adeptus Custodes', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Adeptus Mechanicus', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Aeldari', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Astra Militarum', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Asuryani', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Chaos', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Death Guard', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Deathwatch', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Drukhari', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Elucidean Starstriders', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Gellerpox Infected', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Genestealer Cults', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Grey Knights', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Harlequins', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Heretic Astartes', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Imperium', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Kroot', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Necrons', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Orks', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Servants of the Abyss', ladder_name: '/killteam')
  Faction.create!(faction_name: 'T\'au Empire', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Thousand Sons', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Tyranids', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Imperial Knights', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Chaos Knights', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Demons', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Dark Mechanicus', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Fallen', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Space Wolves', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Dark Angels', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Adepta Sororitas', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Blood Angels', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Khorne', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Tzeentch', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Slaanesh', ladder_name: '/killteam')
  Faction.create!(faction_name: 'Nurgle', ladder_name: '/killteam')

  Faction.create!(faction_name: 'Garrek\'s Reavers', ladder_name: '/underworlds')
  Faction.create!(faction_name: 'Steelheart\'s Champions', ladder_name: '/underworlds')
  Faction.create!(faction_name: 'Sepulchral Guard', ladder_name: '/underworlds')
  Faction.create!(faction_name: 'Ironskull\'s Boyz', ladder_name: '/underworlds')
  Faction.create!(faction_name: 'The Chosen Axes', ladder_name: '/underworlds')
  Faction.create!(faction_name: 'Spiteclaw\'s Swarm', ladder_name: '/underworlds')
  Faction.create!(faction_name: 'The Farstriders', ladder_name: '/underworlds')
  Faction.create!(faction_name: 'Magore\'s Fiends', ladder_name: '/underworlds')
  Faction.create!(faction_name: 'Stormsire\'s Cursebreakers', ladder_name: '/underworlds')
  Faction.create!(faction_name: 'Thorns of the Brian Queen', ladder_name: '/underworlds')
  Faction.create!(faction_name: 'Eyes of the Nine', ladder_name: '/underworlds')
  Faction.create!(faction_name: 'Zarbag\'s Gitz', ladder_name: '/underworlds')
  Faction.create!(faction_name: 'Mollog\'s Mob', ladder_name: '/underworlds')
  Faction.create!(faction_name: 'Godsworn Hunt', ladder_name: '/underworlds')
  Faction.create!(faction_name: 'Thundrik\'s Profiteers', ladder_name: '/underworlds')
  Faction.create!(faction_name: 'Ylthari\'s Guardians', ladder_name: '/underworlds')

  Faction.create!(faction_name: 'Adeptus Astartes', ladder_name: '/40k')
  Faction.create!(faction_name: 'Adeptus Custodes', ladder_name: '/40k')
  Faction.create!(faction_name: 'Adeptus Mechanicus', ladder_name: '/40k')
  Faction.create!(faction_name: 'Aeldari', ladder_name: '/40k')
  Faction.create!(faction_name: 'Astra Militarum', ladder_name: '/40k')
  Faction.create!(faction_name: 'Asuryani', ladder_name: '/40k')
  Faction.create!(faction_name: 'Chaos', ladder_name: '/40k')
  Faction.create!(faction_name: 'Death Guard', ladder_name: '/40k')
  Faction.create!(faction_name: 'Deathwatch', ladder_name: '/40k')
  Faction.create!(faction_name: 'Drukhari', ladder_name: '/40k')
  Faction.create!(faction_name: 'Elucidean Starstriders', ladder_name: '/40k')
  Faction.create!(faction_name: 'Gellerpox Infected', ladder_name: '/40k')
  Faction.create!(faction_name: 'Genestealer Cults', ladder_name: '/40k')
  Faction.create!(faction_name: 'Grey Knights', ladder_name: '/40k')
  Faction.create!(faction_name: 'Harlequins', ladder_name: '/40k')
  Faction.create!(faction_name: 'Heretic Astartes', ladder_name: '/40k')
  Faction.create!(faction_name: 'Imperium', ladder_name: '/40k')
  Faction.create!(faction_name: 'Kroot', ladder_name: '/40k')
  Faction.create!(faction_name: 'Necrons', ladder_name: '/40k')
  Faction.create!(faction_name: 'Orks', ladder_name: '/40k')
  Faction.create!(faction_name: 'Servants of the Abyss', ladder_name: '/40k')
  Faction.create!(faction_name: 'T\'au Empire', ladder_name: '/40k')
  Faction.create!(faction_name: 'Thousand Sons', ladder_name: '/40k')
  Faction.create!(faction_name: 'Tyranids', ladder_name: '/40k')
  Faction.create!(faction_name: 'Imperial Knights', ladder_name: '/40k')
  Faction.create!(faction_name: 'Chaos Knights', ladder_name: '/40k')
  Faction.create!(faction_name: 'Demons', ladder_name: '/40k')
  Faction.create!(faction_name: 'Dark Mechanicus', ladder_name: '/40k')
  Faction.create!(faction_name: 'Fallen', ladder_name: '/40k')
  Faction.create!(faction_name: 'Space Wolves', ladder_name: '/40k')
  Faction.create!(faction_name: 'Dark Angels', ladder_name: '/40k')
  Faction.create!(faction_name: 'Adepta Sororitas', ladder_name: '/40k')
  Faction.create!(faction_name: 'Blood Angels', ladder_name: '/40k')
  Faction.create!(faction_name: 'Khorne', ladder_name: '/40k')
  Faction.create!(faction_name: 'Tzeentch', ladder_name: '/40k')
  Faction.create!(faction_name: 'Slaanesh', ladder_name: '/40k')
  Faction.create!(faction_name: 'Nurgle', ladder_name: '/40k')

  def change
    f = Faction.find_by(faction_name: 'Transition')
    transition_id = f.id
    add_column(:teams, :faction_id, :integer, null: false, default: transition_id)
  end

end
